version: '3'

services:
  youtube-converter:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./downloads:/app/downloads
    restart: unless-stopped
    environment:
      - PORT=5000
      - FLASK_ENV=production 